### PR TITLE
🐛 Fix types on addSteps and context

### LINKED ISSUE #281: ShepherdTour type definition incorrectly expects instances of Step class for steps property
The type definition for the React Component ShepherdTour declares that the steps property must be an array of instances of the Step class. This is not how the README documents that the library should be used.

This means simply copying the example from the README causes a type check error. 

```
Type '({ id: string; text: string[]; attachTo: { element: string; on: string; }; classes: string; buttons: ({ type: string; classes: string; text: string; } | { type: string; text: string; classes?: undefined; })[]; title?: undefined; scrollTo?: undefined; } | { ...; } | { ...; } | { ...; } | { ...; })[]' is not assignable to type 'Step[]'.
  Type '{ id: string; text: string[]; attachTo: { element: string; on: string; }; classes: string; buttons: ({ type: string; classes: string; text: string; } | { type: string; text: string; classes?: undefined; })[]; title?: undefined; scrollTo?: undefined; } | { ...; } | { ...; } | { ...; } | { ...; }' is not assignable to type 'Step'.
    Type '{ id: string; text: string[]; attachTo: { element: string; on: string; }; classes: string; buttons: ({ type: string; classes: string; text: string; } | { type: string; text: string; classes?: undefined; })[]; title?: undefined; scrollTo?: undefined; }' is missing the following properties from type 'Step': cancel, complete, destroy, getTour, and 8 more.
```

That's with the below code.

```ts
import React, { Component, useContext } from "react";
import { ShepherdTour, ShepherdTourContext } from "react-shepherd";
import "shepherd.js/dist/css/shepherd.css";

const newSteps = [
  {
    id: "welcome",
    text: [
      `
      <p>
      Shepherd is a JavaScript library for guiding users through your app.
      It uses <a href="http://tether.io/">Tether</a>,
      another open source library, to render dialogs for each tour "step".
      </p>
      <p>
      Among many things, Tether makes sure your steps never end up off screen or
      cropped by an overflow. (Try resizing your browser to see what we mean.)
      </p>
      `
    ],
    attachTo: { element: ".hero-welcome", on: "bottom" },
    classes: "shepherd shepherd-welcome",
    buttons: [
      {
        type: "cancel",
        classes: "shepherd-button-secondary",
        text: "Exit"
      },
      {
        type: "next",
        text: "Next"
      }
    ]
  },
  {
    id: "installation",
    title: "Installation",
    text:
      "Installation is simple, if you are using npm or yarn, just install like any other package.",
    attachTo: { element: ".install-element", on: "bottom" },
    buttons: [
      {
        type: "back",
        classes: "shepherd-button-secondary",
        text: "Back"
      },
      {
        type: "next",
        text: "Next"
      }
    ]
  },
  {
    id: "usage",
    title: "Usage",
    text: [
      "To use the tour service, simply inject it into your application and use it like this example."
    ],
    attachTo: { element: ".usage-element", on: "bottom" },
    buttons: [
      {
        type: "back",
        classes: "shepherd-button-secondary",
        text: "Back"
      },
      {
        type: "next",
        text: "Next"
      }
    ]
  },
  {
    id: "modal",
    attachTo: {
      element: ".modal-element",
      on: "top"
    },
    buttons: [
      {
        type: "back",
        classes: "shepherd-button-secondary",
        text: "Back"
      },
      {
        type: "next",
        text: "Next"
      }
    ],
    classes: "custom-class-name-1 custom-class-name-2",
    text: [
      `<p>
        We implemented true modal functionality by disabling clicking of the rest of the page.
      </p>
      <p>
        If you would like to enable modal, simply add <code>useModalOverlay: true</code> to your tourOptions object.
      </p>`
    ]
  },
  {
    id: "centered-example",
    title: "Centered Shepherd Element",
    text: `But attachment is totally optional!\n \
    Without a target, a tour step will create an element that's centered within the view. \
    Check out the <a href="https://shipshapecode.github.io/shepherd/">documentation</a> to learn more.`,
    buttons: [
      {
        type: "back",
        classes: "shepherd-button-secondary",
        text: "Back"
      },
      {
        type: "next",
        text: "Next"
      }
    ]
  },
  {
    id: "followup",
    title: "Learn more",
    text: "Star Shepherd on Github so you remember it for your next project",
    attachTo: { element: ".hero-followup", on: "top" },
    scrollTo: true,
    buttons: [
      {
        type: "back",
        classes: "shepherd-button-secondary",
        text: "Back"
      },
      {
        type: "next",
        text: "Done"
      }
    ]
  }
];

const tourOptions = {
  defaultStepOptions: {
    cancelIcon: {
      enabled: true
    }
  },
  useModalOverlay: true
};

export default class App extends Component {
  render() {
    return (
      <div>
        <ShepherdTour steps={newSteps} tourOptions={tourOptions}>
          <Content />
        </ShepherdTour>
      </div>
    );
  }
}

function Content() {
  const tour = useContext(ShepherdTourContext);

  return (
    <div>
      <button className="button dark" onClick={tour.start}>
        Start Tour
      </button>
    </div>
  );
}
```

Additionally, the type checker doesn't know the type of the return value of `useContext(ShepherdTourContext)`

### PR DESCRIPTION
**Pull request by chuckcarpenter**
closes #281

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -4,15 +4,15 @@ import Step from 'shepherd.js/src/types/step';
...
+  steps: Array<Step.StepOptions>;
   tourOptions: Tour.TourOptions;
 }
 
 interface ShepherdStepWithType extends Step.StepOptionsButton {
   type?: string;
 }
 
-const ShepherdTourContext = React.createContext({});
+const ShepherdTourContext = React.createContext(Tour);
```
Comment (nathggns) [inline src/index.tsx]: I might be confused but I'm not sure this is actually what you want? The `ShepherdTourContext` is supposed to contain an instance of `Tour`, whereas you're defaulting it to class object here instead. I think a more suitable alternative would be

```ts
React.createContext<Tour | null>(null);
```

which represents what is actually happening.

This would require people to check there's actually an active tour when consuming the context, but they should have been doing that anyway if value could have been `{}` instead of an instance of the tour.

Comment (nathggns) [reply src/index.tsx]: If you don't want to break people's code who haven't been checking for this, you could do 

```ts
React.createContext<Tour | {}>({});
```

though using `{}` as a default doesn't seem sensible in the long term.

Comment (chuckcarpenter) [reply src/index.tsx]: Since we're major bumping the Shepherd version next, we'll just make this a breaking change.
